### ISSUE TITLE
Mise à jour RimWorld 1.1.2605 rev1126 (25 TODO)

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#316]
Mise à jour RimWorld 1.1.2605 rev1126 (25 TODO)
ATTENTION : Les fichiers de traduction précédents auront des bugs dans les quêtes Hospitality avec cette version du jeu ! Récuperez absolument ces nouveaux fichiers.

- [x] Core/Backstories/Backstories.xml (2 TODO)
- [x] Royalty/DefInjected/ThingDef/Buildings_MusicalInstruments.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml
- [x] Royalty/DefInjected/AbilityDef/Abilities.xml
- [x] Royalty/Keyed/Misc_Gameplay.xml
- [x] Royalty/Keyed/Dialog_StatReports.xml
